### ISSUE TITLE
Opacity attribute not implemented in style tag

### ISSUE THREAD

**Issue by bassamdevmob** [zathras/jovial_svg#32]
There is a problem with some svg pictures, borders appear on the edges of the `CustomPainter` for example this [picture](https://iqtest.vileo.net/storage/images/answer/phNVE8smPYr6TyBMtKNbpQZQ7p64dVVe5vUXGQPY.svg) 
shows:
![capture](https://user-images.githubusercontent.com/121380056/209466486-170e882f-fa59-492d-8c2c-660246e093c2.jpg)

**Comment by zathras** [comment]
The issue is the opacity property in the style.  That image actually has a border; it's just made 99% transparent through its style.  The opacity property needs some special handling because, unlike other properties, it's not inherited down the document tree.  When this was implemented, opacity in a style wasn't implemented properly, or wasn't implemented; I'll have to dig into the code a bit.

This modified SVG shows the issue well.

![opacity_in_style](https://user-images.githubusercontent.com/20762139/209569570-f3ddf033-3269-4eb5-94a5-9678f076546a.svg)

**Comment by zathras** [comment]
Hi Bassam,

This latest commit should fix the issue.  Could you try out this version of the library with any other problem images, and any other test images you have handy?

After I hear back from you, I'll publish as 1.1.9; for now, it's published as https://pub.dev/packages/jovial_svg/versions/1.1.9-rc.1 -- I think you can just specify version "1.1.9-rc.1" in your pubspec.yaml file.

Thanks,

Bill

**Comment by bassamdevmob** [comment]
Hi Bill,

**Comment by zathras** [comment]
Published as 1.1.9
