### ISSUE TITLE
bug in version 1.1.10 using IOS

### ISSUE THREAD

**Issue by rafagazani** [zathras/jovial_svg#42]
hosted/pub.dartlang.org/jovial_svg-1.1.10/lib/src/affine.dart:59:24: Error: Member not found: 'IndexError.withLength'.
          throw IndexError.withLength(row, 3, indexable: this);
                           ^^^^^^^^^^

**Comment by rafagazani** [comment]
Flutter 3.3.9
Dart 2.18.5  

When trying to use version 1.1.7 pub.dev is pointing to 1.1.10.
In a project from 12/2022 version 1.1.7 worked but now it is pointing to release 1.1.10

**Comment by zathras** [comment]
You're running an quite old version of Flutter!  Your choices are to upgrade to a contemporary flutter that uses SDK 2.19, or downgrade to jovial_svg version 1.1.9 in your pubspec.yaml.

Google made an annoying, trivial API change, and made it more or less mandatory by aggressively deprecating the old API.  Their toolchain apparently doesn't catch this sort of thing.  I'll publish 1.11 (requiring a current SDK) and withdraw 1.10, but you'll have to manually upgrade your SDK or downgrade your jovial_svg, because I think withdrawing a package has no effect on workspaces where it has already been downloaded.

**Comment by zathras** [comment]
Oops, referenced wrong issue in that commit.  Should have been #48.
