### ISSUE TITLE
Incorrect path rendering

### ISSUE THREAD

**Issue by fischermario** [zathras/jovial_svg#51]
While evaluating jovial_svg I stumbled across a problem regarding certain shapes with arcs. My SVG was created with Inkscape and exported as "Plain SVG".

This is what the image is supposed to look like (rendered by Chrome):
<img width="63" alt="Bildschirmfoto 2023-04-16 um 18 41 16" src="https://user-images.githubusercontent.com/10214295/232327583-cdc37dd2-78be-4d8f-8be4-692e33461e22.png">

I have tested it with Chrome, the GNOME image viewer (EOG) and Gwenview.

This is what is being rendered by jovial_svg:
<img width="63" alt="Bildschirmfoto 2023-04-16 um 18 40 48" src="https://user-images.githubusercontent.com/10214295/232327866-c0159e2e-bbbf-4d80-a2ca-1757bc78741d.png">

This is the example file:
[example.svg](https://user-images.githubusercontent.com/10214295/232327651-0687047c-0fa2-4dc2-8742-c56685fb7f12.svg)

Investigating further I found out that there must be some parser issue with the path:

m 147.20783,222.91196
a 4.020851,7.3433791 **_86.8724_** 0 1 -7.22968,-3.80559
v -40.60221
a 7.3433791,4.020851 3.12763 0 1 7.22968,-3.80559 4.020851,7.3433791 **_86.8724_** 0 1 7.22968,3.80559
v 40.60221
a 7.3433791,4.020851 3.12763 0 1 -7.22968,3.80559
z

When you set the the angle of the two arcs to 0 (numbers in bold characters) you get the same effect in the other viewers. I suspect that the angle value is incorrectly interpreted by jovial_svg.

**Comment by zathras** [comment]
Thank you for spotting this, and doing the detective work!

It was a radians/degrees problem.  When I parse the SVG, I convert the angle to radians.  The Dart API takes degrees.

I must have noticed that the SVG spec said degrees, and I must have assumed that the Dart API took radians (because every API in every programming language I've used since Applesoft BASIC has worked in radians).  Nope; for this one API, Dart went with degrees.  Cue sad trombone.

I'll have to add a regression test for this, but the fix is simple (see next putback.)
