### ISSUE TITLE
svg duplicated in listview

### ISSUE THREAD

**Issue by danbeyene** [zathras/jovial_svg#56]
the package works fine with a single SVG image, but when it comes to Listview. it duplicates some of the images
![Screenshot_20230430_164001](https://user-images.githubusercontent.com/40373577/235356037-ccc79132-5af1-408e-99f4-c163b1c48d20.png)

**Comment by zathras** [comment]
Unlikely; this is probably a bug in the code that manages the list view, which is not a part of `jovial_svg`.

If this were a bug in the library, at a minimum you would need to include code or enough information so that the problem can be easily reproduced.  Generally, this means providing a short stand-alone program that shows the problem.
