### ISSUE TITLE
 StateError: Bad state: A Dart object attempted to access a native peer

### ISSUE THREAD

**Issue by ahmdaeyz** [zathras/jovial_svg#62]
**Describe the bug**
We keep getting this error fetching network SVGs (sometimes)

`StateError: Bad state: A Dart object attempted to access a native peer, but the native peer has been collected (nullptr). This is usually the result of calling methods on a native-backed object when the native resources have already been disposed.`

Here is how we are creating the widget:
```dart
final _cache = ScalableImageCache(size: 150);
SizedBox(
              width: widget.width,
              height: widget.height,
              child: ScalableImageWidget.fromSISource(
                  isComplex: true,
                  cache: _cache,
                  onError: (_) => widget.errorWidget ?? SizedBox.shrink(),
                  onLoading: (_) =>
                      widget.placeholderWidget ?? SizedBox.shrink(),
                  alignment: widget.alignment,
                  fit: widget.fit,
                  background: widget.color,
                  si: ScalableImageSource.fromSvgHttpUrl(
                    Uri.parse(widget.image!),)))
```

**Additional context**
Here is the stacktrace:
```dart
StateError: Bad state: A Dart object attempted to access a native peer, but the native peer has been collected (nullptr). This is usually the result of calling methods on a native-backed object when the native resources have already been disposed.
  File "errors_patch.dart", line 135, in StateError._throwNew
  File "painting.dart", in Codec.dispose
  File "common.dart", line 945, in _ImageLoader.unprepare
    _codec?.dispose();
  File "common.dart", line 844, in SIImage.unprepare
    void unprepare() => loader.unprepare();
  File "exported.dart", line 768, in ScalableImageBase.unprepareImages
    im.unprepare();
...
(135 additional frame(s) were not displayed)
```

**Comment by ahmdaeyz** [comment]
I'm not sure if this is related to the package. Pointers is really appreciated.

**Comment by zathras** [comment]
That's a bug in flutter, I'm afraid.  Specifically, it's a bug in the image handling code, in `dart:ui`.

`jovial_svg` is just calling `Codec.unprepare` in `dart:ui`.  This area of flutter has had issues dealing with native memory before -- see, for example, https://pub.dev/documentation/jovial_svg/latest/jovial_svg/ImageDisposeBugWorkaround.html

**Comment by ahmdaeyz** [comment]
@zathras Do you by any chance know of a workaround? Or at least if the bug is reported to the flutter team?

Thanks!

**Comment by billf-pshs** [comment]
I don't know if anyone else has reported this to the flutter team, but I encourage you to report it.  A good practice would be to put a link to this issue in the bug report.

As to workarounds, you could downgrade to a prior version of Flutter that doesn't have this bug.  I don't know what version that would be, but I'd guess this bug was introduced pretty recently.

You could also try setting `imageDisposeBugWorkaround` as described at https://pub.dev/documentation/jovial_svg/latest/jovial_svg/ScalableImage/imageDisposeBugWorkaround.html .  That does have the effect of not doing as good a job of cleaning up native memory (which is why the Flutter classes have the `dispose` method in the first place); it's unlikely but possible that you could run into memory issues if you have a lot of SVGs with embedded images.

If the flutter team is unresponsive when you file a bug, I could put in some code to swallow the exception.  Before I do that, I'd want a link to the Flutter bug you submit, so I can reference it in the source code, and the changelog.

**Comment by zathras** [comment]
Taking another look at this, `jovial_svg` could at least catch the error, and print a warning about the bug in the Flutter library being ignored.  Also, `ImageDisposeBugWorkaround` could have an option added to suppress the warning.  Reopening the issue to do that.

BTW, the existing `ImageDisposeBugWorkarround` probably wouldn't help with this Flutter bug.  It's in a different part of the Flutter API than the old bug.

**Comment by zathras** [comment]
Please try with 1.1.16-rc.1, and let me know how it goes.
